name: Microservices using Spring Boot

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0
